2021-08-31 09:35:22,195 INFO    MainThread:77 [wandb_setup.py:_flush():69] setting env: {}
2021-08-31 09:35:22,196 INFO    MainThread:77 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-31 09:35:22,197 INFO    MainThread:77 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '2ad32f3610515f9a3f89d3c177d5ce2690622d49'}
2021-08-31 09:35:22,198 INFO    MainThread:77 [wandb_init.py:_log_setup():342] Logging user logs to /content/drive/My Drive/YoloObjectDetection/wandb/run-20210831_093522-1xxpkdu3/logs/debug.log
2021-08-31 09:35:22,198 INFO    MainThread:77 [wandb_init.py:_log_setup():343] Logging internal logs to /content/drive/My Drive/YoloObjectDetection/wandb/run-20210831_093522-1xxpkdu3/logs/debug-internal.log
2021-08-31 09:35:22,200 INFO    MainThread:77 [wandb_init.py:init():375] calling init triggers
2021-08-31 09:35:22,200 INFO    MainThread:77 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-08-31 09:35:22,200 INFO    MainThread:77 [wandb_init.py:init():397] re-initializing run, found existing run on stack: scmfiz90
2021-08-31 09:35:22,203 INFO    MainThread:77 [wandb_run.py:finish():1271] finishing run nahid-ebrahimian/Yolo5s-ObjectDetection/scmfiz90
2021-08-31 09:35:22,209 INFO    MainThread:77 [jupyter.py:save_history():353] not saving jupyter history
2021-08-31 09:35:22,210 INFO    MainThread:77 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-08-31 09:35:22,210 INFO    MainThread:77 [wandb_init.py:_jupyter_teardown():275] cleaning up jupyter logic
2021-08-31 09:35:22,211 INFO    MainThread:77 [wandb_run.py:_atexit_cleanup():1571] got exitcode: 0
2021-08-31 09:35:22,212 INFO    MainThread:77 [wandb_run.py:_restore():1543] restore
2021-08-31 09:35:22,950 INFO    MainThread:77 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 684
  total_bytes: 684
}

2021-08-31 09:35:23,145 INFO    MainThread:77 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 684
  total_bytes: 684
}

2021-08-31 09:35:23,253 INFO    MainThread:77 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 684
  total_bytes: 10984
}

2021-08-31 09:35:23,357 INFO    MainThread:77 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1014
  total_bytes: 10984
}

2021-08-31 09:35:23,461 INFO    MainThread:77 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10984
  total_bytes: 10984
}

2021-08-31 09:35:23,565 INFO    MainThread:77 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10984
  total_bytes: 10984
}

2021-08-31 09:35:23,667 INFO    MainThread:77 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10984
  total_bytes: 10984
}

2021-08-31 09:35:23,823 INFO    MainThread:77 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10984
  total_bytes: 10984
}

2021-08-31 09:35:23,926 INFO    MainThread:77 [wandb_run.py:_wait_for_finish():1693] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10984
  total_bytes: 10984
}

2021-08-31 09:35:25,280 INFO    MainThread:77 [wandb_run.py:_show_files():1915] logging synced files
2021-08-31 09:35:25,300 INFO    MainThread:77 [wandb_init.py:init():424] starting backend
2021-08-31 09:35:25,303 INFO    MainThread:77 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-08-31 09:35:25,311 INFO    MainThread:77 [backend.py:ensure_launched():135] starting backend process...
2021-08-31 09:35:25,318 INFO    MainThread:77 [backend.py:ensure_launched():140] started backend process with pid: 840
2021-08-31 09:35:25,322 INFO    MainThread:77 [wandb_init.py:init():429] backend started and connected
2021-08-31 09:35:25,405 INFO    MainThread:77 [wandb_run.py:_label_probe_notebook():815] probe notebook
2021-08-31 09:35:26,850 INFO    MainThread:77 [wandb_init.py:init():477] updated telemetry
2021-08-31 09:35:26,852 INFO    MainThread:77 [wandb_init.py:init():500] communicating current version
2021-08-31 09:35:26,924 INFO    MainThread:77 [wandb_init.py:init():505] got version response 
2021-08-31 09:35:26,924 INFO    MainThread:77 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-31 09:35:27,013 INFO    MainThread:77 [wandb_init.py:init():540] starting run threads in backend
2021-08-31 09:35:28,823 INFO    MainThread:77 [wandb_run.py:_console_start():1601] atexit reg
2021-08-31 09:35:28,832 INFO    MainThread:77 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.WRAP
2021-08-31 09:35:28,832 INFO    MainThread:77 [wandb_run.py:_redirect():1512] Wrapping output streams.
2021-08-31 09:35:28,837 INFO    MainThread:77 [wandb_run.py:_redirect():1536] Redirects installed.
2021-08-31 09:35:28,838 INFO    MainThread:77 [wandb_init.py:init():565] run started, returning control to user process
